// Custom Arsenal Preset
GRLIB_arsenal_weapons = [
    "arifle_MX_GL_khk_F",
    "hgun_P07_khk_F",
    "arifle_MXC_khk_F",
    "arifle_MX_khk_F",
    "launch_MRAWS_green_F",
    "SMG_01_F",
    "MMG_02_black_F",
    "arifle_MXM_khk_F",
    "arifle_SDAR_F",
    "hgun_P07_F",
    "srifle_LRR_tna_F",
    "srifle_DMR_02_F",
    "arifle_MXM_Black_F",
    "Laserdesignator_01_khk_F"
];

GRLIB_arsenal_magazines = [
    "30Rnd_65x39_caseless_khaki_mag",
    "30Rnd_65x39_caseless_khaki_mag_Tracer",
    "16Rnd_9x21_Mag",
    "30Rnd_65x39_caseless_mag",
    "MRAWS_HEAT_F",
    "MRAWS_HE_F",
    "30Rnd_45ACP_Mag_SMG_01",
    "130Rnd_338_Mag",
    "20Rnd_556x45_UW_mag",
    "30Rnd_556x45_Stanag_red",
    "7Rnd_408_Mag",
    "16Rnd_9x21_Mag",
    "10Rnd_338_Mag",
    "30Rnd_65x39_caseless_black_mag"
];

GRLIB_arsenal_items = [
    "U_B_T_Soldier_F", //uniforms
    "U_B_T_Soldier_SL_F",
    "U_B_T_Soldier_AR_F",
    "U_B_HeliPilotCoveralls",
    "U_B_PilotCoveralls",
    "U_B_FullGhillie_lsh",
    "U_B_Wetsuit",
    "V_PlateCarrierGL_tna_F", //vests
    "V_PlateCarrier2_tna_F",
    "V_PlateCarrier1_tna_F",
    "V_TacVest_blk",
    "V_Chestrig_oli",
    "V_RebreatherB",
    "H_HelmetB_Enh_tna_F", //helmets
    "H_HelmetB_tna_F",
    "H_HelmetB_Light_tna_F",
    "H_PilotHelmetHeli_B",
    "H_PilotHelmetFighter_B",
    "H_MilCap_tna_F",
    "H_Shemag_olive",
    "H_Booniehat_oli",
    "H_Booniehat_tna_F",
    "H_Cap_oli",
    "H_HelmetB_snakeskin",
    "acc_pointer_IR", //optics and weapon items
    "optic_Hamr_khk_F",
    "optic_LRPS",
    "optic_Holosight",
    "optic_Holosight_khk_F",
    "optic_Holosight_smg",
    "optic_Hamr",
    "muzzle_snds_H_khk_F",
    "muzzle_snds_acp",
    "bipod_01_F_blk",
    "muzzle_snds_65_TI_blk_F",
    "ACE_acc_pointer_green",
    "optic_ERCO_khk_F",
    "bipod_01_F_snd",
    "muzzle_snds_H_khk_F",
    "muzzle_snds_L",
    "optic_ERCO_khk_F",
    "optic_AMS_khk",
    "ACE_optic_LRPS_2D",
    "optic_LRPS_tna_F",
    "optic_SOS",
    "optic_DMS",
    "optic_Arco",
    "optic_MRCO",
    "optic_KHS_blk",
    "optic_AMS",
    "optic_Arco_blk_F",
    "MiniGrenade", //grenades
    "HandGrenade",
    "1Rnd_HE_Grenade_shell",
    "SmokeShell",
    "SmokeShellGreen",
    "SmokeShellBlue",
    "SmokeShellOrange",
    "SmokeShellRed",
    "1Rnd_Smoke_Grenade_shell",
    "1Rnd_SmokeBlue_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokeOrange_Grenade_shell",
    "UGL_FlareWhite_F",
    "ACE_HuntIR_M203",
    "Chemlight_green", //chemlights
    "ACE_Chemlight_HiGreen",
    "ACE_Chemlight_HiRed",
    "ACE_Chemlight_IR",
    "ACE_Chemlight_HiBlue",
    "ACE_Clacker", //engineering and sapping
    "ACE_DefusalKit",
    "ToolKit",
    "MineDetector",
    "SatchelCharge_Remote_Mag",
    "DemoCharge_Remote_Mag",
    "APERSMine_Range_Mag",
    "APERSBoundingMine_Range_Mag",
    "ClaymoreDirectionalMine_Remote_Mag",
    "SLAMDirectionalMine_Wire_Mag",
    "Binocular", //gear
    "Rangefinder",
    "FirstAidKit",
    "ItemMap",
    "ItemCompass",
    "ItemWatch",
    "ItemRadio",
    "ItemGPS",
    "SAN_Headlamp_v2",
    "G_B_Diving",
    "NVGoggles_OPFOR",
    "NVGoggles_tna_F",
    "ACE_NVG_Gen4",
    "ACE_NVG_Wide",
    "B_UavTerminal",
    "ACE_VectorDay",
    "Laserbatteries",
    "ACE_EarPlugs", //ace stuff
    "ACE_IR_Strobe_Item",
    "ACE_MapTools",
    "ACE_Flashlight_XL50",
    "ACE_RangeCard",
    "ACE_RangeTable_82mm",
    "ACE_Altimeter",
    "ACE_SpottingScope",
    "ACE_microDAGR",
    "ACE_HuntIR_monitor",
    "ACE_EntrenchingTool",
    "ACE_Kestrel4500",
    "ACE_Tripod",
    "ACE_Flashlight_MX991",
    "ACE_ATragMX",
    "ACE_MX2A",
    "ace_fielddressing", //ace medical
    "ACE_packingbandage",
    "ACE_tourniquet",
    "ACE_elasticBandage",
    "ACE_quikclot",
    "ACE_splint",
    "ACE_bloodIV",
    "ace_morphine",
    "ACE_epinephrine",
    "ACE_surgicalKit",
    "ACE_personalAidKit",
    "ACE_adenosine",
    "ACE_salineIV_500",
    "G_Bandanna_oli", //face
    "G_Bandanna_tan",
    "G_Lowprofile",
    "G_Combat",
    "G_Balaclava_TI_G_tna_F",
    "G_Combat_Goggles_tna_F",
    "G_Sport_Blackred",
    "G_Aviator"
];

GRLIB_arsenal_backpacks = [
    "B_AssaultPack_tna_F",
    "B_Kitbag_sgg",
    "B_Carryall_oli",
    "B_Kitbag_rgr_Exp",
    "B_Mortar_01_weapon_F",
    "B_Mortar_01_support_F",
    "B_UAV_01_backpack_F",
    "B_AssaultPack_blk"
];